---
title: "posts-modeling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries
```{r}
library(stm)
library(ggplot2)
library(tidyverse)
library(wordcloud)
```

## Preprocess dataset
```{r}
data <- read.csv("stm_0330.csv")
processed <- textProcessor(data$p_content, metadata = data)
out <- prepDocuments(processed$documents, processed$vocab, processed$meta,lower.thresh=20)
docs <- out$documents
vocab <- out$vocab
meta <-out$meta
```
## search K
```{r}
storage <- searchK(out$documents, out$vocab, K = c(6,8,10,11,12,14,16,18,20,30), prevalence =~ source, data = meta)
```

### Plot searchK result
```{r}
a <- as.data.frame(lapply(storage$results,unlist)) %>% 
  transmute(K,
            `lower bound` = lbound,
            `Residual` = residual,
            `Semantic coherence` = semcoh,
            `Held-out likelihood` = heldout,
            `em iterations` = em.its,
            `exclusivity` = exclus) %>%
  gather(Metric, Value, -K)%>%
  ggplot(aes(K, Value, color = Metric)) +
  geom_line(size = 1.5, alpha = 0.7, show.legend = FALSE) +
  facet_wrap(~Metric, scales = "free_y") +
  labs(x = "K (number of topics)",
       y = NULL,
       title = "Model diagnostics by number of topics")

plot(a)
```
or
```{r}
plot(storage)
```

## selectModel

### k = 20
```{r}
fit <- stm(documents = out$documents, vocab = out$vocab, K = 20, data = out$meta, content =~ source, prevalence =~ source)
```

```{r}
fitselect<-selectModel(out$documents, out$vocab, K = 20, prevalence =~ source, max.em.its = 75,data = out$meta, runs = 20, seed = 8458159)
```

```{r}
plotModels(fitselect)
selected20<-fitselect$runout[[2]]
plot(selected20)
```

### k = 30
```{r}
fit30 <- stm(documents = out$documents, vocab = out$vocab, K = 30, data = out$meta, content =~ source, prevalence =~ source)
```

```{r}
fitselect30<-selectModel(out$documents, out$vocab, K = 30, prevalence =~ source, max.em.its = 75,data = out$meta, runs = 20, seed = 8458159)
```

```{r}
plotModels(fitselect30)
selected30 <- fitselect30$runout[[2]]
sageLabels(selected30)
```

```{r}
plot(selected30)
```

## representative documents
k=20
```{r}
lst20 <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
thoughts_fit <- findThoughts(fit, texts = out$meta$p_content, topics=lst20) 
fit_topics<-labelTopics(fit, n = 10)[[1]]
thoughts_s20 <- findThoughts(selected20, texts = out$meta$p_content, topics=lst20) 
select_topics<-labelTopics(selected20, n = 10)[[1]]

for (i in 1:20){
  #fit
  topic_fit = paste("Topic",i,":",fit_topics[i,1],fit_topics[i,2],fit_topics[i,3],fit_topics[i,4],fit_topics[i,5],fit_topics[i,6],fit_topics[i,7],fit_topics[i,8], sep=" ")
  
  file_name = paste("documents-plots/stm-20/",i,".png",sep="")
  png(file_name,width = 960, height = 960, units = "px")
  plotQuote(thoughts_fit$docs[[i]],width=70,maxwidth = 750,main=topic_fit,text.cex=1.5)
  dev.off()
  
  # select20
  topic_select20 = paste("Topic",i,":",select_topics[i,1],select_topics[i,2],select_topics[i,3],select_topics[i,4],select_topics[i,5],select_topics[i,6],select_topics[i,7],select_topics[i,8], sep=" ")
  file_name = paste("documents-plots/select-20/",i,".png",sep="")
  png(file_name,width = 960, height = 960, units = "px")
  plotQuote(thoughts_s20$docs[[i]],width=70,maxwidth = 750,main=topic_select20,text.cex=1.5)
  dev.off()
}
```


k=30
```{r}
lst30 <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30)
thoughts_fit30 <- findThoughts(fit30, texts = out$meta$p_content, topics=lst30) 
fit_topics30<-labelTopics(fit30, n = 10)[[1]]
thoughts_s30 <- findThoughts(selected30, texts = out$meta$p_content, topics=lst30) 
select_topics30<-labelTopics(selected30, n = 10)[[1]]

for (i in 1:30){
  #fit30
  topic_fit30 = paste("Topic",i,":",fit_topics30[i,1],fit_topics30[i,2],fit_topics30[i,3],fit_topics30[i,4],fit_topics30[i,5],fit_topics30[i,6],fit_topics30[i,7],fit_topics30[i,8], sep=" ")
  
  file_name = paste("documents-plots/stm-30/",i,".png",sep="")
  png(file_name,width = 960, height = 960, units = "px")
  plotQuote(thoughts_fit30$docs[[i]],width=70,maxwidth = 750,main=topic_fit30,text.cex=1.5)
  dev.off()
  
  # select20
  topic_select30 = paste("Topic",i,":",select_topics30[i,1],select_topics30[i,2],select_topics30[i,3],select_topics30[i,4],select_topics30[i,5],select_topics30[i,6],select_topics30[i,7],select_topics30[i,8], sep=" ")
  file_name = paste("documents-plots/select-30/",i,".png",sep="")
  png(file_name,width = 960, height = 960, units = "px")
  plotQuote(thoughts_s30$docs[[i]],width=70,maxwidth = 750,main=topic_select30,text.cex=1.5)
  dev.off()
}
```

```{r}
# word cloud

for (i in 1:30){
  # stm-30
  file_name = paste("wordcloud-plots/stm-30/",i,".png",sep="")
  png(file_name,width = 960, height =960,res=150, units = "px")
  cloud(fit30,topic=i)
  dev.off()
  
  # selected-30
  file_name = paste("wordcloud-plots/selected-30/",i,".png",sep="")
  png(file_name,width = 960, height =960,res=150, units = "px")
  cloud(selected30,topic=i)
  dev.off()
}

for (i in 1:20){
  # stm-20
  file_name = paste("wordcloud-plots/stm-20/",i,".png",sep="")
  png(file_name,width = 960, height =960,res=150, units = "px")
  cloud(fit,topic=i)
  dev.off()
  
  # selected-20
  file_name = paste("wordcloud-plots/selected-20/",i,".png",sep="")
  png(file_name,width = 960, height =960,res=150, units = "px")
  cloud(selected20,topic=i)
  dev.off()
}

```

## Estimate topic-metadata relationship

### k = 20
```{r}
cov20<- estimateEffect(1:20 ~ source, selected20,  meta = out$meta, uncertainty = "Global")
```

```{r}
plot(cov20, covariate = "source", topics = c(1,2,4,6,7,8,9,10,11,13,14,16,17,19), model = selected20, method = "difference", cov.value1 = "reddit", cov.value2 = "Alzconnected", xlab ="reddit ... Alzconnected", main = "Effect of covariates on topics (K=20)", xlim = c(-.1, .1), labeltype=c("frex"),verbose.labels = F)
```

### k = 30
```{r}
cov30<- estimateEffect(1:30 ~ source, selected30,  meta = out$meta, uncertainty = "Global")
prep30 <- estimateEffect(1:30 ~ source, fit30,  meta = out$meta, uncertainty = "Global")
```

```{r}
summary(cov30, topics=1)
plot(selected30, type = "summary", xlim = c(0, .3))
```

```{r}
out$meta$source <- as.factor(out$meta$source)
prep <- estimateEffect(1:30 ~ source, selected30,  meta = out$meta, uncertainty = "Global")
summary(prep, topics=1)
plot(fit, type = "summary", xlim = c(0, .3))
```

```{r}
# covariance plot

plot(cov30, covariate = "source", topics = c(1,2,4,5,6,13,14,15,16,17,18,21,22,23,25,26,29,30), model = selected30, method = "difference", cov.value1 = "reddit", cov.value2 = "Alzconnected", xlab ="reddit ... Alzconnected", main = "Effect of covariates on topics (K=30)", xlim = c(-.1, .1), labeltype=c("frex"),verbose.labels = F)

# can't display topic names for stm models
plot(prep30, covariate = "source", topics = c(1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15), model = fit30, method = "difference", cov.value1 = "reddit", cov.value2 = "Alzconnected", xlab ="reddit ... Alzconnected", main = "Effect of covariates on topics (STM, K=30)", xlim = c(-.1, .1), labeltype="frex")
```


## topic metadata relationship
 
### k = 20

```{r}
labelTopics(fit,c(1, 2,3,4,5,6,7,8,9,10,11,12,13,14,15))
```

### k = 30

```{r}
plot(prep,"year", method = "continuous",topic=3, model = fit, printlegend = FALSE)
```

```{r}
plot(fit30, type = "perspectives", topics=2)
```

